#!/bin/sh

# Get current directory
REPO=$(dirname $(readlink -f $0))

# Create `.zshenv` in $HOME (this is the only *ALLOWED* dotfile there..)
echo -e "# autogenerated by .files/install.sh\nZDOTDIR=$REPO/zsh" > $HOME/.zshenv

# Installation
ln -fs $REPO/kanshi $XDG_CONFIG_HOME/kanshi
ln -fs $REPO/sway $XDG_CONFIG_HOME/sway
ln -fs $REPO/swaylock $XDG_CONFIG_HOME/swaylock
ln -fs $REPO/vim $XDG_CONFIG_HOME/vim
ln -fs $REPO/tio $XDG_CONFIG_HOME/tio
ln -fs $REPO/zsh $XDG_CONFIG_HOME/zsh
ln -fs $REPO/systemd $XDG_CONFIG_HOME/systemd

# TODO:
# - systemd default.target.wants could be populated by services from this repo
