#!/bin/zsh

export LANG="en_US.UTF-8"
export VISUAL="vim"

export DOTFILEDIR=$(realpath $(dirname $0)/../..)

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

export PATH="$PATH:$HOME/.local/bin"

# Keep application configs in $HOME/.config
export COPILOT_HOME=$HOME/.config/copilot
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export NPM_CONFIG_PREFIX=$HOME/.local
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm



export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket

# CubeIDE dislikes wayland for it's WEBKIT based widgets
export WEBKIT_DISABLE_COMPOSITING_MODE=0

# Configure Modules
compinit -d $HOME/.cache/zcompdump
